# pretzel:
# engine: liquid
title: ""
description: "Imagination Executed Sustainably"
logo-png: https://github.com/idvorkin/blob/raw/master/idvorkin-bunny-ears-ar-2020-547x400.png
logo-url: /
disqus_shortname: idvorkinblog
share: true
dropcap: true
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
url: https://idvork.in

# Owner/author information
owner:
  name: Igor Dvorkin
  avatar: igordvorkin.jpg
  email: idvorkin@gmail.com
  description: Living the good life

# Analytics and webmaster tools stuff goes here
google_analytics: UA-73602282-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Search
    url: /
  - title: Surprise me
    url: /random
  - title: Tags
    url: /tags
  - title: LinkedIn
    url: /linkedin
  - title: Tech Diary
    url: /td
  - title: About
    url: /about

collections:
  d:
    output: true
  td:
    output: true

# See directions @
# https://community.algolia.com/jekyll-algolia/getting-started.html
# Create algolia key via cat
# cat ~/gits/igor2/secretBox.json | jq -r ."AlgoliaKey" > _algolia_api_key

algolia:
  application_id: RY6D0RNCA3
  search_only_api_key: d4bae7d1d6328352ce13c0978ca620e9
  index_name: jekyll
  files_to_exclude:
    - "*bak"
    - "back-refs.json"
    - "*sh"
    - "*py"
    - "search.html"
    - "*index.html"
    - "all.html"
    - "all.md"
    - "tags.html"
    - "tags"

plugins_dir: ["jekyll-paginate", "jekyll-sitemap", "jekyll-redirect-from"]
include: [".htaccess"]
exclude:
  [
    "lib",
    "config.rb",
    "Gemfile",
    "Capfile",
    "Gemfile.lock",
    "config",
    "log",
    "Rakefile",
    "Rakefile.rb",
    "tmp",
    "less",
    "*.sublime-project",
    "*.sublime-workspace",
    "test",
    "spec",
    "Gruntfile.js",
    "package.json",
    "node_modules",
  ]

permalink: /:title
siteurl: "https://idvork.in/"

plugins:
  - jekyll-redirect-from
  - jekyll-paginate
# Allow multiple permalinks for the same post
# https://help.github.com/articles/redirects-on-github-pages/
